const quotes = [
  "À aboyer sans mordre, tu vas te casser les dents. Avant de les détruire, je laisse parler les gens. J'n'aurai jamais d'tour d'ivoire, je n'tue pas l'éléphant",
  "Je boxe avec les mots, Muhammad Ali m'a couronné",
  "J'ai craché sur ton sol, j'n'y mettrai jamais l'genou",
  "Souhaite-nous santé, bonheur, le reste on l'achètera",
  "C'est pas le quartier qui me quitte, c'est moi j'quitte le quartier",
  'Le boule est plat, tu ne fais pas vraiment de squats',
  'Plus j’connais les Hommes, plus j’aime mon rot’; ta provenance, appartenance, on s’en moque',
  "J'ai fait du game une dictature, pour ça qu'on me récompense pas",
  '"Booba", "échec", j\'n\'ai pas trouvé de lien, parler de mes défaites, c\'est ne parler de rien',
  'L.U.N.A, ma petite fille. À m’asseoir sur un banc, en tenant dans ma main tes petits doigts de femme',
  'Ton rire ouvre la mer en deux',
  "Nique ta fondation de merde, j'préfère sauver les animaux",
  "Mon camp c'est le règne animal, là où il n'y a plus de gens. J'veux aller plus haut qu'le sommet de la montagne, là où il n'y a plus de vent",
  "Si t'es un avion de chasse on va s'crasher c'est sûr j'sais pas piloter",
  "Mon prof' m'a dit : \"tu finiras à Nanterre\", je n'voulais pas réussir de toute manière",
  "Ennemis assis sur l'obélisque, quand ça rer-ti, ils obéissent",
  "J'ai creusé tunnel dans son cœur, j'me suis évadé",
  "Ton cercueil ton nouvel habitat, je n'viendrai pas à ta crémaillère",
  "Je perdrais tout pour lui, ne passerai jamais d'l'amour à la haine",
  "Vroum, vroum, j'fais des roues arrières dans l'cul d'ta madre, on peut même pas dire qu't'as mal joué, car t'as pas joué",
  "Si tu cherches l'échec, tu demandes à Kaaris",
  "J'n'ai plus d'besoins que des envies",
  'Le malheur est dans le béton, le bonheur est dans le pré',
  "Nouveau riche, ma Lamborghini a pris quelques dos-d'ânes, j'fais ni la queue au Ritz, ni au McDonald's",
  'On trinque à nos balafres, à nos crochets tous les soirs',
  'Passent les gos, passent les euros, passent les années, ^assent les clashs, guerres, ma carrière est cellophanée',
  "J'lui ai attaché les mains, c'est ses fesses qui applaudissent",
  "Ces fils de putes portent l'œil, j'ai teinté les vitres du double R. Revanche, colère, échec scolaire, dis leur y'a R à Baudelaire, à Molière",
  "J'ai couronne sur la tête pourtant c'est le voisin qui a eu la fève",
  "J'ai du mal avec les humains, car instinct animal",
  "Si j'tue un fils de pute, y a pas mort d'homme. Le drapeau est noir car l'blanc est pour ceux qui abandonnent",
  "Ma longévité dans ce game en dit long, ta carrière en nylon, mes seules barrières sont de corail, j'suis un Benzema à Lyon",
  "J'rentre d'un footing avec Vladimir Poutine",
  "En France comme dans la schneckzer, nègre est à l'étroit",
  "À l'école de la rue j'ai fait Harvard",
  "Tellement d'écus, j'ai pas b'soin d'être beau, elle m'donnerait son cul même si j'étais gros",
  "J'vais te casser le dos, pas te marier. Me tiens pas la main, ça va parler, j'ai déjà l'Balmain baissé sur le palier",
  "J'ai laissé mon cœur ouvert, pensant que tu n'allais rien voler",
  "Trois mojitos, j'sors pepito, dame un besito, pute, p'tit pont dans la schneck à Linda or je force, j'vais droit au but",
  "J'ai fait des erreurs, dans la vie rien ne s'efface, J'suis fait pour une seule femme, pour plusieurs pétasses",
  "Coup d'coude dans ta mère, coup d'coude dans ta mère sur \"Tchikita\". J'espère régner aussi longtemps qu'Abdelaziz Bouteflika",
  "L'argent n'fait pas l'bonheur, bonheur remplit pas l'assiette",
  "T'es au bord du suicide, j'suis au bord de mer, te tuer si tu les touches, c'est mon rôle de père",
  "J'suis un macaque selon Darwin, j'ai une grosse bite selon Marine",
  "J'nique des mères à toute vitesse, ma queue a syndrome de la Tourette",
  "J'ai un cœur tombé du camion, le sourire au bout du canon",
  "Depuis 0.9, ils critiquaient mais ont tous saigné l'autotune",
  'Tu ne baises pas la première-fois ? Moi je ne baise pas la deuxième',
  "On porte des grosses chaînes, on baise des grosses chiennes. Que tu viennes du Bronx ou d'Saint-Étienne, fais pas des tiennes",
  "Pas besoin de pilule du lendemain, j'te crache dans l'nez",
  'Ne fais pas trop de bien ou tu seras cloué sur une croix',
  "La vie mais pas mon rêve, y'a qu'ça qu'tu m'enlèveras",
  "Si y'a embrouille, on négocie pas, t'as pas d'quoi nourrir un Tamagotchi",
  "J'suis avec Théo, on fuck les schmitt, j'rôde avec mon slip en fer",
  "Tu pues d'la chatte, on te Febreze",
  "Si j'te fume c'est pour ton bien, c'est pour qu'tu n'recommences pas",
  "Tu n'peux que gagner quand t'as rien à perdre",
  "Personne dans le monde ne marche du même pas, leurs règles ont toutes une tombe, c'est ça qu'ils n'comprennent pas",
  "Cherche pas les clés d'mon cœur, j'ai que les clés d'la Lambo",
  'Je ne manque de rien, je ne manque que de temps',
  "Les vainqueurs l'écrivent, les vaincus racontent l'histoire",
  "Fuyons d'ici, ma duchesse, rien qu'nous, très loin du reste",
  'La justice a deux vitesses, le Lamborghini en a six',
  "Quand la roue tourne que je t'encule, j'appelle ça le Karmasutra",
  'Nos cœurs battent trop vite, on va se crasher, il faut réduire la vitesse',
  'Personne te regarde comme le handball',
  "J'les baise mais pas sans leurs talons, passe le mot à Cendrillon",
  'Tu n’arriveras jamais comme le feat avec Rohff',
  'Faut battre le fer quand il est chaud, abattre le frère quand il est faux',
  "J'aime l'argent mais je préfère avoir le temps, tu as l'arme, encore faut-il avoir le cran",
  "Dulcinée veut aller au ciné, j'vais lui péter le dos, elle ira juste chez le kiné",
  'Elles sont faites contre nous donc on enfreint les lois',
  "La mort c'est la sœur de la paresse",
  "T'es bonne en cuisine, t'es bonne en legging, j'suis né dans les grands vins, t'es mort dans les vignes",
  "J'ai toujours le mauvais rôle mais je joue que les meilleurs films",
  "Jésus dit de tendre la joue mais je n'suis pas pratiquant"
];

document
  .getElementById('message')
  .appendChild(
    document.createTextNode(quotes[Math.floor(Math.random() * quotes.length)])
  );
